import { Inter } from "next/font/google";
import "./globals.css";
import { Providers } from "./providers";
import NavbarWithSearch from "@/components/navbar/navbar";
import Footer from "@/components/footer/footer";
import CategoriesNavbar from "@/components/categories/categories";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Providers>
          <div className="sticky top-0 z-10">
            <NavbarWithSearch></NavbarWithSearch>
            <CategoriesNavbar></CategoriesNavbar>
          </div>
          {children}
          <Footer />
        </Providers>
      </body>
    </html>
  );
}
